### ISSUE TITLE
Directory for windows.

### ISSUE THREAD

**Issue by arthusu** [caioluders/WBH#2]
The directory for windows must be changed or you can set a conditional if the script runs on windows:

`history_chrome_files = glob.glob(os.path.expanduser("~")+"\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\History")`

`history_firefox_files = glob.glob(os.path.expanduser("~")+"\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\*\\places.sqlite")`

**Comment by b1scoito** [comment]
Made a PR.

**Comment by caioluders** [comment]
Closed because of #3
